services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf 

  django:
    image: pythonbook
    build:
      context: ../../
      dockerfile: ./deploy/subdomain/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ../../:/tdd.pythonbook.com
  
  migrations:
    image: pythonbook
    command: python manage.py migrate --noinput
    volumes:
      - ../../:/tdd.pythonbook.com