services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/subdomain/site.conf:/etc/nginx/conf.d/site.conf 

  django:
    build:
      context: ../../
      dockerfile: ./deploy/build/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
