name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']
        active-chapter: ['chapter25']

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install Dependencies
      run: |
        poetry install
    - name: Run Module Tests
      working-directory: ./${{ matrix.active-chapter }}
      run: |
        poetry run python manage.py test lists accounts
